export { default as Home } from "./Home/Home"
export { default as Post } from "./Post/Post"
export { default as Profile } from "./Profile/Profile"
export { default as SignIn } from "./SignIn/SignIn"
export { default as SignUp } from "./SignUp/SignUp"
